"""Patient Table updated

Revision ID: 75c89debf49c
Revises: 92f49c00fb8a
Create Date: 2020-12-29 12:37:54.046629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c89debf49c'
down_revision = '92f49c00fb8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('previous_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'previous_data')
    # ### end Alembic commands ###
