"""patients table

Revision ID: 927ac566579c
Revises: 2f0fd66a166e
Create Date: 2020-12-21 14:18:26.482452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927ac566579c'
down_revision = '2f0fd66a166e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('posture', sa.Float(), nullable=True),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_email'), 'patient', ['email'], unique=True)
    op.add_column('employee', sa.Column('address', sa.String(length=200), nullable=True))
    op.alter_column('employee', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('employee', 'address')
    op.drop_index(op.f('ix_patient_email'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
